export enum POWERCARD_CARD_TYPE {
  COMP = 'COMP',
  DIAGNOSTICS = 'DIAGNOSTICS',
  EMPLOYEE = 'EMPLOYEE',
  GOLD = 'GOLD',
  POWER = 'POWER',
  POWER_HOUR = 'POWER_HOUR',
  SERVICE = 'SERVICE',
  VIP = 'VIP',
  WHQ_SERVICE = 'WHQ_SERVICE',
}
