export const CUSTOMER_SERVICE_GRAPHQL_CLIENT_TOKEN =
  'CUSTOMER_SERVICE_GRAPHQL_CLIENT_TOKEN';
export const NOTIFICATION_SERVICE_GRAPHQL_CLIENT_TOKEN =
  'NOTIFICATION_SERVICE_GRAPHQL_CLIENT_TOKEN';
export const TRANSACTION_SERVICE_GRAPHQL_CLIENT_TOKEN =
  'TRANSACTION_SERVICE_GRAPHQL_CLIENT_TOKEN';
export const MOBILE_PASS_SERVICE_GRAPHQL_CLIENT_TOKEN =
  'MOBILE_PASS_SERVICE_GRAPHQL_CLIENT_TOKEN';
export const DAVE_AND_BUSTERS_SERVICE_GRAPHQL_CLIENT_TOKEN =
  'DAVE_AND_BUSTERS_SERVICE_GRAPHQL_CLIENT_TOKEN';
export const API_VERIFICATION_SERVICE_GRAPHQL_CLIENT_TOKEN =
  'API_VERIFICATION_SERVICE_GRAPHQL_CLIENT_TOKEN';
export const PAYMENT_SERVICE_GRAPHQL_CLIENT_TOKEN =
  'PAYMENT_SERVICE_GRAPHQL_CLIENT_TOKEN';
export const AUTH_SERVICE_GRAPHQL_CLIENT_TOKEN =
  'AUTH_SERVICE_GRAPHQL_CLIENT_TOKEN';

export const CUSTOMER_GRAPHQL_CLIENT_SERVICE_TOKEN =
  'CUSTOMER_GRAPHQL_CLIENT_SERVICE_TOKEN';
export const NOTIFICATION_GRAPHQL_CLIENT_SERVICE_TOKEN =
  'NOTIFICATION_GRAPHQL_CLIENT_SERVICE_TOKEN';
export const TRANSACTION_GRAPHQL_CLIENT_SERVICE_TOKEN =
  'TRANSACTION_GRAPHQL_CLIENT_SERVICE_TOKEN';
export const MOBILE_PASS_GRAPHQL_CLIENT_SERVICE_TOKEN =
  'MOBILE_PASS_GRAPHQL_CLIENT_SERVICE_TOKEN';
export const DAVE_AND_BUSTERS_GRAPHQL_CLIENT_SERVICE_TOKEN =
  'DAVE_AND_BUSTERS_GRAPHQL_CLIENT_SERVICE_TOKEN';
export const API_VERIFICATION_GRAPHQL_CLIENT_SERVICE_TOKEN =
  'API_VERIFICATION_GRAPHQL_CLIENT_SERVICE_TOKEN';
export const PAYMENT_GRAPHQL_CLIENT_SERVICE_TOKEN =
  'PAYMENT_GRAPHQL_CLIENT_SERVICE_TOKEN';
export const AUTH_GRAPHQL_CLIENT_SERVICE_TOKEN =
  'AUTH_GRAPHQL_CLIENT_SERVICE_TOKEN';

export const GRAPHQL_SERVICE_DIRECTORY_TOKEN =
  'GRAPHQL_SERVICE_DIRECTORY_TOKEN';
