const data = {
  fieldName: 'checkList',
  fieldNodes: [
    {
      kind: 'Field',
      name: {
        kind: 'Name',
        value: 'checkList',
        loc: {
          start: 20,
          end: 29,
        },
      },
      arguments: [
        {
          kind: 'Argument',
          name: {
            kind: 'Name',
            value: 'tableUuid',
            loc: {
              start: 430,
              end: 439,
            },
          },
          value: {
            kind: 'StringValue',
            value: '24ED19B8-9B0E-410A-BC70-F2E6BEF416C7',
            block: false,
            loc: {
              start: 441,
              end: 479,
            },
          },
          loc: {
            start: 430,
            end: 479,
          },
        },
      ],
      directives: [],
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          {
            kind: 'Field',
            name: {
              kind: 'Name',
              value: 'checkOpenTime',
              loc: {
                start: 490,
                end: 503,
              },
            },
            arguments: [],
            directives: [],
            loc: {
              start: 490,
              end: 503,
            },
          },
          {
            kind: 'Field',
            name: {
              kind: 'Name',
              value: 'other',
              loc: {
                start: 508,
                end: 513,
              },
            },
            arguments: [],
            directives: [],
            loc: {
              start: 508,
              end: 513,
            },
          },
          {
            kind: 'Field',
            name: {
              kind: 'Name',
              value: 'payCode',
              loc: {
                start: 518,
                end: 525,
              },
            },
            arguments: [],
            directives: [],
            loc: {
              start: 518,
              end: 525,
            },
          },
          {
            kind: 'Field',
            name: {
              kind: 'Name',
              value: 'payment',
              loc: {
                start: 530,
                end: 537,
              },
            },
            arguments: [],
            directives: [],
            loc: {
              start: 530,
              end: 537,
            },
          },
          {
            kind: 'Field',
            name: {
              kind: 'Name',
              value: 'storeId',
              loc: {
                start: 542,
                end: 549,
              },
            },
            arguments: [],
            directives: [],
            loc: {
              start: 542,
              end: 549,
            },
          },
          {
            kind: 'Field',
            name: {
              kind: 'Name',
              value: 'subTotal',
              loc: {
                start: 554,
                end: 562,
              },
            },
            arguments: [],
            directives: [],
            loc: {
              start: 554,
              end: 562,
            },
          },
          {
            kind: 'Field',
            name: {
              kind: 'Name',
              value: 'tax',
              loc: {
                start: 567,
                end: 570,
              },
            },
            arguments: [],
            directives: [],
            loc: {
              start: 567,
              end: 570,
            },
          },
          {
            kind: 'Field',
            name: {
              kind: 'Name',
              value: 'total',
              loc: {
                start: 575,
                end: 580,
              },
            },
            arguments: [],
            directives: [],
            loc: {
              start: 575,
              end: 580,
            },
          },
          {
            kind: 'Field',
            name: {
              kind: 'Name',
              value: 'rewardPoints',
              loc: {
                start: 589,
                end: 601,
              },
            },
            arguments: [],
            directives: [],
            loc: {
              start: 589,
              end: 601,
            },
          },
          {
            kind: 'Field',
            name: {
              kind: 'Name',
              value: 'lineItems',
              loc: {
                start: 606,
                end: 615,
              },
            },
            arguments: [],
            directives: [],
            selectionSet: {
              kind: 'SelectionSet',
              selections: [
                {
                  kind: 'Field',
                  name: {
                    kind: 'Name',
                    value: 'amount',
                    loc: {
                      start: 624,
                      end: 630,
                    },
                  },
                  arguments: [],
                  directives: [],
                  loc: {
                    start: 624,
                    end: 630,
                  },
                },
                {
                  kind: 'Field',
                  name: {
                    kind: 'Name',
                    value: 'description',
                    loc: {
                      start: 637,
                      end: 648,
                    },
                  },
                  arguments: [],
                  directives: [],
                  loc: {
                    start: 637,
                    end: 648,
                  },
                },
                {
                  kind: 'Field',
                  name: {
                    kind: 'Name',
                    value: 'itemType',
                    loc: {
                      start: 655,
                      end: 663,
                    },
                  },
                  arguments: [],
                  directives: [],
                  loc: {
                    start: 655,
                    end: 663,
                  },
                },
                {
                  kind: 'Field',
                  name: {
                    kind: 'Name',
                    value: 'lineNumber',
                    loc: {
                      start: 670,
                      end: 680,
                    },
                  },
                  arguments: [],
                  directives: [],
                  loc: {
                    start: 670,
                    end: 680,
                  },
                },
                {
                  kind: 'Field',
                  name: {
                    kind: 'Name',
                    value: 'quantity',
                    loc: {
                      start: 687,
                      end: 695,
                    },
                  },
                  arguments: [],
                  directives: [],
                  loc: {
                    start: 687,
                    end: 695,
                  },
                },
                {
                  kind: 'Field',
                  name: {
                    kind: 'Name',
                    value: 'seat',
                    loc: {
                      start: 702,
                      end: 706,
                    },
                  },
                  arguments: [],
                  directives: [],
                  loc: {
                    start: 702,
                    end: 706,
                  },
                },
              ],
              loc: {
                start: 616,
                end: 712,
              },
            },
            loc: {
              start: 606,
              end: 712,
            },
          },
        ],
        loc: {
          start: 484,
          end: 716,
        },
      },
      loc: {
        start: 20,
        end: 716,
      },
    },
  ],
  returnType: '[Check]',
  parentType: 'Query',
  path: {
    key: 'checkList',
  },
  schema: {
    __validationErrors: [],
    astNode: {
      kind: 'SchemaDefinition',
      directives: [],
      operationTypes: [
        {
          kind: 'OperationTypeDefinition',
          operation: 'query',
          type: {
            kind: 'NamedType',
            name: {
              kind: 'Name',
              value: 'Query',
            },
          },
        },
        {
          kind: 'OperationTypeDefinition',
          operation: 'mutation',
          type: {
            kind: 'NamedType',
            name: {
              kind: 'Name',
              value: 'Mutation',
            },
          },
        },
        {
          kind: 'OperationTypeDefinition',
          operation: 'subscription',
          type: {
            kind: 'NamedType',
            name: {
              kind: 'Name',
              value: 'Subscription',
            },
          },
        },
      ],
    },
    __allowedLegacyNames: [],
    _queryType: 'Query',
    _mutationType: 'Mutation',
    _subscriptionType: 'Subscription',
    _directives: [
      '@inAuthPayloadValidate',
      '@adminOnly',
      '@skip',
      '@include',
      '@deprecated',
    ],
    _typeMap: {
      Query: 'Query',
      InAuthGetSigfilesResponse: 'InAuthGetSigfilesResponse',
      String: 'String',
      LoggedInTest: 'LoggedInTest',
      Boolean: 'Boolean',
      Int: 'Int',
      Customer: 'Customer',
      ID: 'ID',
      PersonName: 'PersonName',
      OCEmailAddress: 'OCEmailAddress',
      Address: 'Address',
      GeoLocation: 'GeoLocation',
      Float: 'Float',
      PaymentInstrument: 'PaymentInstrument',
      PAYMENT_INSTRUMENT_TYPE: 'PAYMENT_INSTRUMENT_TYPE',
      PaymentInstrumentExpiration: 'PaymentInstrumentExpiration',
      PAYMENT_INSTRUMENT_STATUS: 'PAYMENT_INSTRUMENT_STATUS',
      PaymentProvider: 'PaymentProvider',
      LoyaltyInstrument: 'LoyaltyInstrument',
      LOYALTY_INSTRUMENT_STATUS: 'LOYALTY_INSTRUMENT_STATUS',
      Powercard: 'Powercard',
      POWERCARD_STATUS_TYPE: 'POWERCARD_STATUS_TYPE',
      POWERCARD_CARD_TYPE: 'POWERCARD_CARD_TYPE',
      PowercardImagePack: 'PowercardImagePack',
      PowercardImage: 'PowercardImage',
      OCURL: 'OCURL',
      WalletPassUrl: 'WalletPassUrl',
      Demographics: 'Demographics',
      OCDate: 'OCDate',
      OCJSON: 'OCJSON',
      ContactPhoneNumber: 'ContactPhoneNumber',
      OCPhoneNumber: 'OCPhoneNumber',
      PHONE_TYPE: 'PHONE_TYPE',
      CUSTOMER_STATUS: 'CUSTOMER_STATUS',
      CustomerAgreement: 'CustomerAgreement',
      BrandAgreement: 'BrandAgreement',
      OCDateTime: 'OCDateTime',
      Brand: 'Brand',
      Tenant: 'Tenant',
      BrandCustomerPreference: 'BrandCustomerPreference',
      CustomerPreference: 'CustomerPreference',
      PreferenceValue: 'PreferenceValue',
      CustomerLoginAttemptFilter: 'CustomerLoginAttemptFilter',
      GeoLocationFilter: 'GeoLocationFilter',
      GeoLocationCreate: 'GeoLocationCreate',
      CustomerDeviceFilter: 'CustomerDeviceFilter',
      CustomerLoginAttemptConnection: 'CustomerLoginAttemptConnection',
      CustomerLoginAttemptEdge: 'CustomerLoginAttemptEdge',
      CustomerLoginAttempt: 'CustomerLoginAttempt',
      CustomerDevice: 'CustomerDevice',
      PageInfo: 'PageInfo',
      Location: 'Location',
      LocationAttribute: 'LocationAttribute',
      LocationResource: 'LocationResource',
      LOCATION_RESOURCE_TYPE: 'LOCATION_RESOURCE_TYPE',
      ResourceItemFilter: 'ResourceItemFilter',
      RESOURCE_ITEM_TYPE: 'RESOURCE_ITEM_TYPE',
      ResourceItemConnection: 'ResourceItemConnection',
      ResourceItemEdge: 'ResourceItemEdge',
      ResourceItem: 'ResourceItem',
      ResourceItemPrice: 'ResourceItemPrice',
      LOCATION_RESOURCE_STATUS: 'LOCATION_RESOURCE_STATUS',
      OpenCommerceFeature: 'OpenCommerceFeature',
      HoursOfOperationGroup: 'HoursOfOperationGroup',
      HoursOfOperation: 'HoursOfOperation',
      WEEKDAY: 'WEEKDAY',
      TransactionFilter: 'TransactionFilter',
      TRANSACTION_STATUS: 'TRANSACTION_STATUS',
      LoyaltyInstrumentFilter: 'LoyaltyInstrumentFilter',
      TransactionPaymentInfoFilter: 'TransactionPaymentInfoFilter',
      LocationFilter: 'LocationFilter',
      LocationAttributeFilter: 'LocationAttributeFilter',
      LocationResourceFilter: 'LocationResourceFilter',
      BrandFilter: 'BrandFilter',
      OpenCommerceFeatureFilter: 'OpenCommerceFeatureFilter',
      HARDWARE_VENDOR: 'HARDWARE_VENDOR',
      TRANSACTION_TYPE: 'TRANSACTION_TYPE',
      PAYMENT_LEVEL: 'PAYMENT_LEVEL',
      LOYALTY_LEVEL: 'LOYALTY_LEVEL',
      FUEL_PUMP_STATUS: 'FUEL_PUMP_STATUS',
      TransactionConnection: 'TransactionConnection',
      TransactionEdge: 'TransactionEdge',
      Transaction: 'Transaction',
      ItemCurrency: 'ItemCurrency',
      STAC: 'STAC',
      TransactionPaymentInfo: 'TransactionPaymentInfo',
      TransactionItem: 'TransactionItem',
      ItemPrice: 'ItemPrice',
      TRANSACTION_ITEM_TYPE: 'TRANSACTION_ITEM_TYPE',
      ReceiptLine: 'ReceiptLine',
      FuelReceipt: 'FuelReceipt',
      TRANSACTION_PURCHASE_TYPE: 'TRANSACTION_PURCHASE_TYPE',
      TransactionPaymentEvent: 'TransactionPaymentEvent',
      TRANSACTION_EVENT_TYPE: 'TRANSACTION_EVENT_TYPE',
      ClientToken: 'ClientToken',
      Check: 'Check',
      CheckLineItem: 'CheckLineItem',
      CHECK_LINE_ITEM_TYPE: 'CHECK_LINE_ITEM_TYPE',
      RateCardFilter: 'RateCardFilter',
      OFFER_PAYMENT_TYPE: 'OFFER_PAYMENT_TYPE',
      RateCard: 'RateCard',
      RateCardItem: 'RateCardItem',
      RateCardCategory: 'RateCardCategory',
      LocationConnection: 'LocationConnection',
      LocationEdge: 'LocationEdge',
      AppConfig: 'AppConfig',
      Image: 'Image',
      BackgroundImage: 'BackgroundImage',
      PayAtTableConfig: 'PayAtTableConfig',
      PaymentConfig: 'PaymentConfig',
      RewardHistory: 'RewardHistory',
      RewardTransaction: 'RewardTransaction',
      PowercardOfferList: 'PowercardOfferList',
      PowercardOffer: 'PowercardOffer',
      OFFER_TYPE: 'OFFER_TYPE',
      PowercardOfferListResponse: 'PowercardOfferListResponse',
      PowercardConfigItem: 'PowercardConfigItem',
      FeaturesResponse: 'FeaturesResponse',
      Feature: 'Feature',
      DAVE_AND_BUSTERS_FEATURE: 'DAVE_AND_BUSTERS_FEATURE',
      FeatureEnabledResponse: 'FeatureEnabledResponse',
      TriggerException: 'TriggerException',
      Mutation: 'Mutation',
      AccessTokenByRefreshTokenInputType: 'AccessTokenByRefreshTokenInputType',
      AuthTokens: 'AuthTokens',
      Tokens: 'Tokens',
      CustomerOTPRequest: 'CustomerOTPRequest',
      OTP_CHANNEL: 'OTP_CHANNEL',
      OTP_MODE: 'OTP_MODE',
      CustomerOTPPayload: 'CustomerOTPPayload',
      OTP: 'OTP',
      CustomerOTPPayloadOrAuthTokens: 'CustomerOTPPayloadOrAuthTokens',
      InauthTrustScoreValueInput: 'InauthTrustScoreValueInput',
      InAuthDeviceRegistrationRequestInput:
        'InAuthDeviceRegistrationRequestInput',
      InAuthDeviceRegistrationResponse: 'InAuthDeviceRegistrationResponse',
      CustomerRegistrationComplete: 'CustomerRegistrationComplete',
      CustomerPersonNameCreate: 'CustomerPersonNameCreate',
      CustomerDemographicsCreate: 'CustomerDemographicsCreate',
      CustomerPreferenceCreate: 'CustomerPreferenceCreate',
      PreferenceValueCreate: 'PreferenceValueCreate',
      CustomerCreate: 'CustomerCreate',
      CustomerAddressCreate: 'CustomerAddressCreate',
      CustomerAgreementCreate: 'CustomerAgreementCreate',
      CustomerPhoneNumberCreate: 'CustomerPhoneNumberCreate',
      CustomerCreateVerify: 'CustomerCreateVerify',
      CustomerUpdate: 'CustomerUpdate',
      CustomerPersonNameUpdate: 'CustomerPersonNameUpdate',
      CustomerAddressUpdate: 'CustomerAddressUpdate',
      GeoLocationUpdate: 'GeoLocationUpdate',
      CustomerDemographicsUpdate: 'CustomerDemographicsUpdate',
      CustomerPhoneNumberUpdate: 'CustomerPhoneNumberUpdate',
      CustomerPreferenceUpdate: 'CustomerPreferenceUpdate',
      BrandCustomerPreferenceUpdate: 'BrandCustomerPreferenceUpdate',
      PreferenceValueUpdate: 'PreferenceValueUpdate',
      CustomerPaymentInstrumentCreate: 'CustomerPaymentInstrumentCreate',
      PaymentInstrumentExpirationInput: 'PaymentInstrumentExpirationInput',
      CustomerPaymentInstrumentVerify: 'CustomerPaymentInstrumentVerify',
      CustomerPaymentInstrumentUpdate: 'CustomerPaymentInstrumentUpdate',
      CustomerLoyaltyInstrumentCreate: 'CustomerLoyaltyInstrumentCreate',
      CustomerLoyaltyInstrumentUpdate: 'CustomerLoyaltyInstrumentUpdate',
      CustomerPasswordSet: 'CustomerPasswordSet',
      CustomerPassword: 'CustomerPassword',
      CustomerPasswordChange: 'CustomerPasswordChange',
      CustomerPasswordCredentials: 'CustomerPasswordCredentials',
      CustomerUsername: 'CustomerUsername',
      AuthPayload: 'AuthPayload',
      CustomerPasswordResetByOTPVerify: 'CustomerPasswordResetByOTPVerify',
      CustomerPasswordReset: 'CustomerPasswordReset',
      CustomerPasswordResetPaymentInstrumentVerify:
        'CustomerPasswordResetPaymentInstrumentVerify',
      CustomerDeviceCreate: 'CustomerDeviceCreate',
      CustomerDeviceUpdate: 'CustomerDeviceUpdate',
      CheckPaymentApplyInput: 'CheckPaymentApplyInput',
      BillingInput: 'BillingInput',
      PowercardConfigItemInput: 'PowercardConfigItemInput',
      PowercardCreate: 'PowercardCreate',
      PowercardAttributesUpdate: 'PowercardAttributesUpdate',
      PowercardFundsAdd: 'PowercardFundsAdd',
      Response: 'Response',
      VirtualPowercardCreate: 'VirtualPowercardCreate',
      CustomerPinCodeSet: 'CustomerPinCodeSet',
      CustomerPinCode: 'CustomerPinCode',
      CustomerPinCodeChange: 'CustomerPinCodeChange',
      CustomerPinCodeVerify: 'CustomerPinCodeVerify',
      Subscription: 'Subscription',
      __Schema: '__Schema',
      __Type: '__Type',
      __TypeKind: '__TypeKind',
      __Field: '__Field',
      __InputValue: '__InputValue',
      __EnumValue: '__EnumValue',
      __Directive: '__Directive',
      __DirectiveLocation: '__DirectiveLocation',
      TransactionStart: 'TransactionStart',
      OCTime: 'OCTime',
      OtpInput: 'OtpInput',
      AuthChallenge: 'AuthChallenge',
      AuthChallengeType: 'AuthChallengeType',
      SignUpInput: 'SignUpInput',
      UserAttributes: 'UserAttributes',
      Node: 'Node',
      AccessTokenByRefreshTokenInput: 'AccessTokenByRefreshTokenInput',
      MOBILE_DEVICE_TYPE: 'MOBILE_DEVICE_TYPE',
      CustomerOTPVerify: 'CustomerOTPVerify',
      CustomerPinCodeCredentials: 'CustomerPinCodeCredentials',
      CustomerContact: 'CustomerContact',
      CUSTOMER_REQUEST_TYPE: 'CUSTOMER_REQUEST_TYPE',
      CustomerFeedback: 'CustomerFeedback',
      LocationCheckIn: 'LocationCheckIn',
      CustomerOTPPayloadOrAuthPayload: 'CustomerOTPPayloadOrAuthPayload',
      TransactionServiceError: 'TransactionServiceError',
      Rating: 'Rating',
      PinCodeInputType: 'PinCodeInputType',
      ChangePinCodeInputType: 'ChangePinCodeInputType',
    },
    _possibleTypeMap: {
      CustomerOTPPayloadOrAuthTokens: {
        CustomerOTPPayload: true,
        AuthTokens: true,
      },
    },
    _implementations: {},
    _extensionsEnabled: true,
  },
  fragments: {},
  operation: {
    kind: 'OperationDefinition',
    operation: 'query',
    name: {
      kind: 'Name',
      value: 'checkList',
      loc: {
        start: 6,
        end: 15,
      },
    },
    variableDefinitions: [],
    directives: [],
    selectionSet: {
      kind: 'SelectionSet',
      selections: [
        {
          kind: 'Field',
          name: {
            kind: 'Name',
            value: 'checkList',
            loc: {
              start: 20,
              end: 29,
            },
          },
          arguments: [
            {
              kind: 'Argument',
              name: {
                kind: 'Name',
                value: 'tableUuid',
                loc: {
                  start: 430,
                  end: 439,
                },
              },
              value: {
                kind: 'StringValue',
                value: '24ED19B8-9B0E-410A-BC70-F2E6BEF416C7',
                block: false,
                loc: {
                  start: 441,
                  end: 479,
                },
              },
              loc: {
                start: 430,
                end: 479,
              },
            },
          ],
          directives: [],
          selectionSet: {
            kind: 'SelectionSet',
            selections: [
              {
                kind: 'Field',
                name: {
                  kind: 'Name',
                  value: 'checkOpenTime',
                  loc: {
                    start: 490,
                    end: 503,
                  },
                },
                arguments: [],
                directives: [],
                loc: {
                  start: 490,
                  end: 503,
                },
              },
              {
                kind: 'Field',
                name: {
                  kind: 'Name',
                  value: 'other',
                  loc: {
                    start: 508,
                    end: 513,
                  },
                },
                arguments: [],
                directives: [],
                loc: {
                  start: 508,
                  end: 513,
                },
              },
              {
                kind: 'Field',
                name: {
                  kind: 'Name',
                  value: 'payCode',
                  loc: {
                    start: 518,
                    end: 525,
                  },
                },
                arguments: [],
                directives: [],
                loc: {
                  start: 518,
                  end: 525,
                },
              },
              {
                kind: 'Field',
                name: {
                  kind: 'Name',
                  value: 'payment',
                  loc: {
                    start: 530,
                    end: 537,
                  },
                },
                arguments: [],
                directives: [],
                loc: {
                  start: 530,
                  end: 537,
                },
              },
              {
                kind: 'Field',
                name: {
                  kind: 'Name',
                  value: 'storeId',
                  loc: {
                    start: 542,
                    end: 549,
                  },
                },
                arguments: [],
                directives: [],
                loc: {
                  start: 542,
                  end: 549,
                },
              },
              {
                kind: 'Field',
                name: {
                  kind: 'Name',
                  value: 'subTotal',
                  loc: {
                    start: 554,
                    end: 562,
                  },
                },
                arguments: [],
                directives: [],
                loc: {
                  start: 554,
                  end: 562,
                },
              },
              {
                kind: 'Field',
                name: {
                  kind: 'Name',
                  value: 'tax',
                  loc: {
                    start: 567,
                    end: 570,
                  },
                },
                arguments: [],
                directives: [],
                loc: {
                  start: 567,
                  end: 570,
                },
              },
              {
                kind: 'Field',
                name: {
                  kind: 'Name',
                  value: 'total',
                  loc: {
                    start: 575,
                    end: 580,
                  },
                },
                arguments: [],
                directives: [],
                loc: {
                  start: 575,
                  end: 580,
                },
              },
              {
                kind: 'Field',
                name: {
                  kind: 'Name',
                  value: 'rewardPoints',
                  loc: {
                    start: 589,
                    end: 601,
                  },
                },
                arguments: [],
                directives: [],
                loc: {
                  start: 589,
                  end: 601,
                },
              },
              {
                kind: 'Field',
                name: {
                  kind: 'Name',
                  value: 'lineItems',
                  loc: {
                    start: 606,
                    end: 615,
                  },
                },
                arguments: [],
                directives: [],
                selectionSet: {
                  kind: 'SelectionSet',
                  selections: [
                    {
                      kind: 'Field',
                      name: {
                        kind: 'Name',
                        value: 'amount',
                        loc: {
                          start: 624,
                          end: 630,
                        },
                      },
                      arguments: [],
                      directives: [],
                      loc: {
                        start: 624,
                        end: 630,
                      },
                    },
                    {
                      kind: 'Field',
                      name: {
                        kind: 'Name',
                        value: 'description',
                        loc: {
                          start: 637,
                          end: 648,
                        },
                      },
                      arguments: [],
                      directives: [],
                      loc: {
                        start: 637,
                        end: 648,
                      },
                    },
                    {
                      kind: 'Field',
                      name: {
                        kind: 'Name',
                        value: 'itemType',
                        loc: {
                          start: 655,
                          end: 663,
                        },
                      },
                      arguments: [],
                      directives: [],
                      loc: {
                        start: 655,
                        end: 663,
                      },
                    },
                    {
                      kind: 'Field',
                      name: {
                        kind: 'Name',
                        value: 'lineNumber',
                        loc: {
                          start: 670,
                          end: 680,
                        },
                      },
                      arguments: [],
                      directives: [],
                      loc: {
                        start: 670,
                        end: 680,
                      },
                    },
                    {
                      kind: 'Field',
                      name: {
                        kind: 'Name',
                        value: 'quantity',
                        loc: {
                          start: 687,
                          end: 695,
                        },
                      },
                      arguments: [],
                      directives: [],
                      loc: {
                        start: 687,
                        end: 695,
                      },
                    },
                    {
                      kind: 'Field',
                      name: {
                        kind: 'Name',
                        value: 'seat',
                        loc: {
                          start: 702,
                          end: 706,
                        },
                      },
                      arguments: [],
                      directives: [],
                      loc: {
                        start: 702,
                        end: 706,
                      },
                    },
                  ],
                  loc: {
                    start: 616,
                    end: 712,
                  },
                },
                loc: {
                  start: 606,
                  end: 712,
                },
              },
            ],
            loc: {
              start: 484,
              end: 716,
            },
          },
          loc: {
            start: 20,
            end: 716,
          },
        },
      ],
      loc: {
        start: 16,
        end: 718,
      },
    },
    loc: {
      start: 0,
      end: 718,
    },
  },
  variableValues: {},
  cacheControl: {
    cacheHint: {
      maxAge: 0,
    },
  },
};

export const mockCheckResolveInfo = JSON.parse(JSON.stringify(data));
